# Done to increase the memory available.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.4
loader_version=0.19.3

maven_group = com.coloryr.allmusic.client
archives_base_name = [fabric-1.21.4]AllMusic_Client

fabric_version=0.119.4+1.21.4
