# Done to increase the memory available.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

maven_group = com.coloryr.allmusic.client
archives_base_name = [fabric-26.1]AllMusic_Client

fabric_api_version=0.145.1+26.1
